courses/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.all_courses, name='courses_list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='course'),
    url(r'^accounts/', include('allauth.urls'), name='account'),
]

learning_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.hello_world, name='home'),

]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    content = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

courses/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from .models import Course, Step
# Create your views here.

def all_courses(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses':courses})

def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_project/views.py
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse

def hello_world(request):
    return render(request, 'index.html')

courses/templates/courses/course_detail.html
 {% extends "layout.html" %}
 {% block title %} {{course.title }} {% endblock %}
 {% block content %}

 <div class="container">
     <h2>{{ course.title }}</h2>
     {{ course.description }}

     <div class="row">
         {% for step in course.step_set.all %}
         <div class="col-sm-4">
             <a href="{% url 'courses:step' course.id step.pk %}"><h3>{{ step.title }}</h3></a>
             {{ step.description }}
         </div>
         {% endfor %}
     </div>
 </div>

 {% endblock %}

courses/templates/courses/course_list.html
{% extends 'layout.html' %}

{% block title %}All Our Courses{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        {% for course in courses %}
        <div class="col-sm-4">
            <a href="{% url 'courses:course' course.pk %}"><h2>{{ course.title }}</h2></a>
            {{ course.description }}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends 'layout.html' %}

{% block title %}{{ step.title }} - {{ step.course.title }} {% endblock %}

{% block content %}
<div class="container">
    <h2>{{ step.course.title }}</h2>
    <h3>{{ step.title }}</h3>
    {{ step.description|linebreaks }}
    {{ step.content|linebreaks }}
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %} Welcome to Learning {% endblock %}

{% block content %}
<div class="container">
<h1>Welcome to Learning</h1>
<img src="{% static 'images/logo.jpg' %}" class="img-rounded img-responsive" >
</div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load socialaccount %}


<!doctype html>
<html lang="en">
    <head>
        <title>{% block title %} {% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% load bootstrap3 %}

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        {% block bootstrap3_content %}
        <div class="container">
        <nav class="nav navbar-default">
            <div class="navbar-header">
                 <a class="navbar-brand" href="{% url 'home' %}">LNG</a>
            </div>
            <div id="navbar" class="navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a class="btn btn-link btn-xs" href="{% url 'courses:courses_list' %}">Courses</a></li>
                {% if course.title %}
                <li><a class="btn btn-link btn-xs" href="">: {{ course.title }}</a></li>
                {% elif step.course.title %}
                <li><a class="btn btn-link btn-xs" href="{% url 'courses:course' step.course.pk %}">: {{ step.course.title }}</a></li>
                <li><a class="btn btn-link btn-xs" href="">: {{ step.title }}</a></li>
                {% endif %}
            </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="">Your Account</a></li>

                </ul>
            </div>

        </nav>

            {% block content %} {% endblock content %}

        </div>
    </body>
        {% bootstrap_messages %}

        {% endblock %}


</html>